export const motivosMovimientoStock = [
  { value: "+/-Cambio de precio", label: "+/-Cambio de precio" },
  { value: "+Compra de Mercaderia", label: "+Compra de Mercaderia" },
  { value: "-Venta no Registrada", label: "-Venta no Registrada" },
  { value: "+/-Ajuste Manual de Stock", label: "+/-Ajuste Manual de Stock" },
  { value: "+Reposicion de Proveedor", label: "+Reposicion de Proveedor" },
  { value: "-Devolucion a Proveedor", label: "-Devolucion a Proveedor" },
  { value: "+Devolucion de Cliente", label: "+Devolucion de Cliente" },
  { value: "-Reposicion a Cliente", label: "-Reposicion a Cliente" },
  { value: "-Rotura/Daño/Vencimiento", label: "-Rotura/Daño/Vencimiento" },
  { value: "+Inventario Inicial", label: "+Inventario Inicial" },
  { value: "-Consumo Interno", label: "-Consumo Interno" },
  { value: "-Hurto o Pérdida", label: "-Hurto o Pérdida" },
  { value: "+Transferencia Recibida", label: "+Transferencia Recibida" },
  { value: "-Transferencia Enviada", label: "-Transferencia Enviada" },
  { value: "+Corrección de Conteo", label: "+Corrección de Conteo" },
  { value: "-Error de Carga", label: "-Error de Carga" },
  { value: "+Promoción/Bonificación", label: "+Promoción/Bonificación" },
  { value: "-Muestra Gratis Entregada", label: "-Muestra Gratis Entregada" },
  { value: "+Recupero de Stock", label: "+Recupero de Stock" }
];
